name: Configure pyenv and pick the right version
on: [push, pull_request]

jobs:
 # python installtion
  install-python:
  # should run on linux based operating system
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install python version
      # use the pyenv-action version 7
        uses: gabrielfalcao/pyenv-action@v7
        with:
          default: 3.8.6 # pick 3.8.6 verion 
          command: pip install -U pip  # upgrade pip after installing python
      
      - name: create environment
        run: pyenv local 3.6.5 && python -mvenv .venv365

      - name: Install dependencies
        run: pip install -r requirements.txt --upgrade pip


      - name: setup pyenv
        id: pyenv_installation
        uses: "gabrielfalcao/pyenv-action@v7"

      - name: debug pyenv
        run: echo ${{ steps.pyenv_installation.outputs.pyenv_root }}